### PR TITLE
implement a partial credit score system

### PR DESCRIPTION
**Pull request by victor-zhao-ibm**
DCO 1.1 Signed-off-by: Xinyun Zhao Victor.Zhao@ibm.com

### CODE REVIEW

**Comment by amchaney** [comment]
I still want to update the README to include info on partial credit mapping, and then run a test to verify that everything is still working without the partial credit table.

**Comment by amchaney** [comment]
pending review from @ajainghub

**Comment by ajainghub** [comment]
This is looking good. Ran fine with and without partial credit mapping configured in the config.ini.

**Comment by amchaney** [comment]
DCO 1.1 Signed-off-by: Anna Chaney amchaney@us.ibm.com

**Pull request merged**
