### PR TITLE
87 notebook ws

### PR DESCRIPTION
**Pull request by ajainghub**
Please review the Watson Studio Python Notebook for WA-Testing-Tool... try it in Watson Studio. Basically adds a directory notebook_ws that has instructions and the .ipynb notebook.

### CODE REVIEW

**Comment by andrewrfreed** [comment]
Suggested updates for the documentation:
a) You can refer to this link for “Create a Watson Studio project”:
https://dataplatform.cloud.ibm.com/projects/create-project

b) Please move the “Create the project token” steps ABOVE the “insert token” steps - most users probably don’t have a project created yet.

**Comment by ajainghub** [comment]
Thanks for the feedback Andrew. I'll work on incorporating your suggestions:
1) Word doc to a Markdown file
2) Test/resolve the error you encountered
3) Add reference to "Create a Watson Studio project”
4) Update the steps to move the “Create the project token” steps ABOVE the “insert token” steps
Thanks.

**Comment by ajainghub** [comment]
1. I have updated and added the instructions to a markdown file - GettingStarted.md 
2. Instructions need to be updated in the .ipynb file (to make them consistent with md file)
3. The error appears to be a result of the recent ibm_watson library changes and still needs to be investigated.

**Comment by ajainghub** [comment]
DCO 1.0 Signed-off-by: Anuj Jain jainanuj@us.ibm.com

**Comment by andrewrfreed** [comment]
Solves #87

**Pull request merged**
