### PR TITLE
Fixes for WA-Testing-Tool-WS-Python-Notebook.ipynb

### PR DESCRIPTION
**Pull request by acpang**
Address defects:
[179](https://github.com/cognitive-catalyst/WA-Testing-Tool/issues/179) - WA Testing Tool Notebook errors in section 3. Analyze the results
[180](https://github.com/cognitive-catalyst/WA-Testing-Tool/issues/180) - Python Notebook - Section 3 function call typo
[181](https://github.com/cognitive-catalyst/WA-Testing-Tool/issues/181) - Python Notebook configured to WA url scheduled for deprecation on May 26, 2021

_Note:  Github does not do a good job showing diff changes with Python notebook.  Please reference defect issue for the description of the fix applied w/ screen capture._ 

DCO 1.1 Signed-off-by: Andrew Pang apang@us.ibm.com

### CODE REVIEW

**Comment by andrewrfreed** [comment]
@acpang I believe the original notebook was stored after deleting all the outputs.  In your new update did you also clear all the outputs?  It seems like the diff should only be a handful of lines, not the ~2000 Github is claiming.

**Comment by andrewrfreed** [comment]
@acpang @victorpovar @ajainghub 

For a more proper diff please use `nbdiff`: https://nbdime.readthedocs.io/en/latest/

The steps I followed were:
1) Copy original notebook to `original.ipynb`
2) `jupyter notebook`
3) Open each notebook in the Jupyter view
  a) Clear All Outputs
  b) Save and Checkpoint
4) `nbdiff original.ipynb WA-Testing-Tool-WS-Python-Notebook.ipynb`

This diff is "only" 437 lines, most of which are caused by the re-identing that happened after the mode-check if-blocks were added.

**Comment by acpang** [comment]
Hi @andrewrfreed,

Thx for the advice on the diff tool.

I cleared out the outputs on the notebook and checked it in.  I also ran the nbdime tool against it to check the differences.  Turns out that the original had outputs as well!    

I attached the diff file output for review.  
 
[Notebook_Diff_03112021.pdf](https://github.com/cognitive-catalyst/WA-Testing-Tool/files/6126122/Notebook_Diff_03112021.pdf)

**Comment by andrewrfreed** [comment]
Thanks @acpang , I've learned a bit more about Notebooks since the initial commit!  Your diff looks good to me.

**Review by andrewrfreed — APPROVED** [review]
Thanks for the work!

**Comment by andrewrfreed** [comment]
@victorpovar @ajainghub anything you want to add before we merge this?

**Comment by andrewrfreed** [comment]
Taking the silence as approval.  Nice job @acpang .

**Pull request merged**
