### PR TITLE
#166 adds curl commands for dependencies

### LINKED ISSUE #166: Update sample notebook to pull in supporting files via curl
The following code block in the sample notebook makes setting up the notebook easier - particularly useful as the notebook is copied/pasted or moved around - pulling the supporting scripts via github link eases the setup process.

Code snippet looks like:
```
!curl -O https://raw.githubusercontent.com/cognitive-catalyst/WA-Testing-Tool/master/log_analytics/extractConversations.py
!curl -O https://raw.githubusercontent.com/cognitive-catalyst/WA-Testing-Tool/master/log_analytics/getAllLogs.py

```

### PR DESCRIPTION
**Pull request by modlanglais**
Fixes #166: updates sample notebook to add curl commands for downloading dependencies

DCO 1.1 Signed-off-by: Morgan Langlais <morganlanglais@ibm.com>

### CODE REVIEW

**Comment by modlanglais** [comment]
@andrewrfreed if you want to take a look at this

**Review by andrewrfreed — COMMENTED** [review]
Looks good, just need your DCO in the PR description!

**Comment by modlanglais** [comment]
@andrewrfreed Done! Thanks.

**Review by andrewrfreed — APPROVED** [review]
Nicely done, thanks!

**Pull request merged**
